### ISSUE TITLE
Improve layout and responsiveness of the header

### ISSUE THREAD

**Issue by GypsyDangerous** [DisStreamChat/Website#9]
Currently the header has alot of issues on small screens like the logo not being centered. the hamburger menu not being perfectly centered and some unwanted text wrapping. We probably need to either rewrite the layout of the header or improve the css to make it the header look good on all screen sizes.

**Comment by gaurav3030** [comment]
Can I work on this issue?
I have already, forked, and made some changes to header.scss  file for max-width 900px screen
I made the menu option and logo centered and made text relative to vw for screens with a width more than  900px
![responsive 900](https://user-images.githubusercontent.com/40709484/93570425-9e15a380-f9b0-11ea-9e7f-004a981c340f.PNG)

**Comment by GypsyDangerous** [comment]
Yeah, feel free to make a pr. Thanks 😀! Can you post pictures of different screen sizes either on here or when you make the pr
